# Generated by Django 4.1 on 2022-10-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiyapp', '0001_initial'),
        ('userapp', '0003_remove_sotuvchi_user_sotuvchi_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1)),
                ('sana', models.DateField(auto_now=True)),
                ('jami', models.PositiveSmallIntegerField(default=1)),
                ('tolandi', models.PositiveSmallIntegerField()),
                ('nasiya', models.PositiveSmallIntegerField()),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.mijoz')),
                ('sotuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.sotuvchi')),
            ],
        ),
    ]
